### ISSUE TITLE
configure does not check that sphinx is available

### ISSUE THREAD

**Issue by amahboubi** [maximedenes/coq#42]
#### Version

Commit  `28ce265713` of the sphinx/ssr branch

#### Operating system

Linux/Ubuntu

#### Description of the problem

If sphinx becomes a way to build coqtop, what about testing and displaying its availability at configure time?

**Comment by maximedenes** [comment]
Hmmm. In principle, it does check. Can you give the steps to reproduce the pb?

Did you pass `-with-doc yes` to `configure`?

**Comment by amahboubi** [comment]
No, indeed. (I blindly followed @gares ' instructions in his message :) ). Sorry for the noise.

**Comment by maximedenes** [comment]
> I blindly followed @gares ' instructions in his message

That's a typical mistake :D

**Comment by amahboubi** [comment]
So with the `-with-doc-yes` option I indeed get the suggestion

`You can run `pip3 install antlr4-python3-runtime` to install it.`

**Comment by maximedenes** [comment]
The message may be missing some packages, though, since it was before we added e.g. the biblio.

**Comment by maximedenes** [comment]
If that's the case, please let me know, I'll update the message.

**Comment by amahboubi** [comment]
I think the message can be improved: I am not sure every user will know what pip3 is. On ubuntu at least synaptic will not find "pip3" and the doc of python3-pip is:
"alternative Python package installer - Python 3 version of the package"

(since the current mainstream version of the package is v2.7)

**Comment by amahboubi** [comment]
@gares tells me that installing debian/ubuntu's sphinx packages wouldn't work so what should I do:
- install pip3
- install antlr4-python3-runtime with pip3 
and I will be good?
or is there any other package I should add on top of that?

**Comment by maximedenes** [comment]
Did @gares also not point you to the migrating instructions? ;)

https://github.com/maximedenes/coq/blob/sphinx-doc/doc/sphinx/MIGRATING

**Comment by amahboubi** [comment]
Oh,I see... Indeed, I did not know about this page...Thanks a lot. I am really sorry about this fuss for nothing. Unfortunately the time I allocated to this for today is coming to its end but I will follow the instructions tomorrow.

**Comment by amahboubi** [comment]
Anyway, I think my issue still make sense wrt the improvement of the message emitted by the configure.
